name: Test

on:
  pull_request:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '**/README.md'
      - 'LICENSE*'

jobs:
  linux:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    strategy:
      matrix:
        otp_version: [25, 26]
    
    name: Linux x86_64 - OTP ${{ matrix.otp_version }}

    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp_version }}
          elixir-version: 1.15

      - name: Compile and Test
        run: |
          mix deps.get
          mix elixir_make.precompile
          mix test

  windows:
    runs-on: windows-latest
    env:
      MIX_ENV: test
    strategy:
      matrix:
        otp_version: [25, 26]

    name: Windows x86_64 - OTP ${{ matrix.otp_version }}

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp_version }}
          elixir-version: 1.15

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Compile and Test
        shell: bash
        run: |
          mix deps.get
          mix elixir_make.precompile
          mix test

  macos:
    runs-on: macos-11
    env:
      MIX_ENV: test
      elixir_version: "1.15.2"
    strategy:
      matrix:
        otp_version: ["25.3.2.3", "26.0.2"]

    name: macOS x86_64 - OTP ${{ matrix.otp_version }}

    steps:
      - uses: actions/checkout@v3

      - name: macOS setup
        run: |
          brew install autoconf coreutils curl git openssl asdf
          asdf plugin add erlang https://github.com/asdf-vm/asdf-erlang.git
          asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
          export KERL_CONFIGURE_OPTIONS="--disable-debug --without-javac"
          asdf install erlang ${{ matrix.otp_version }}
          asdf install elixir ${{ env.elixir_version }}
          asdf global erlang ${{ matrix.otp_version }}
          asdf global elixir ${{ env.elixir_version }}
          source $(brew --prefix asdf)/libexec/asdf.sh
          mix local.hex --force
          mix local.rebar --force

      - name: Compile and Test
        run: |
          source $(brew --prefix asdf)/libexec/asdf.sh
          mix deps.get
          mix elixir_make.precompile
          mix test
