name: macos-precompile

on:
  push:
    tags:
      - 'v*'

jobs:
  precompile:
    runs-on: macos-11
    env:
      STB_IMAGE_PREFER_PRECOMPILED: "NO"
      MIX_ENV: "dev"
    strategy:
      fail-fast: true
      matrix:
        include:
          - pair:
              triplet: x86_64-apple-darwin
          - pair:
              triplet: arm64-apple-darwin
              cxx_flags: "-arch arm64"

    steps:
      - uses: actions/checkout@v3

      - name: Install Erlang and Elixir
        run: |
          brew install erlang elixir
          mix local.hex --force
          mix local.rebar --force

      - name: Create precompiled library
        run: |
          if [ "${{ matrix.pair.cxx_flags }}" != "" ]; then
            export CXXFLAGS="${{ matrix.pair.cxx_flags }}"
          fi
          mix deps.get
          mix compile
          export PKG_NAME=stb_image-${{ matrix.pair.triplet }}-${GITHUB_REF##*/}
          mkdir -p "${PKG_NAME}"
          cp -a _build/${MIX_ENV}/lib/stb_image/priv "${PKG_NAME}"
          cd "${PKG_NAME}/priv/"
          zip -r -9 -y "../../${PKG_NAME}.zip" "."
          cd ../../
          rm -rf "${PKG_NAME}"
          ls -lah "${PKG_NAME}.zip"
          mkdir -p artifacts
          mv "${PKG_NAME}.zip" artifacts

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifacts/stb_image-*.zip
