name: precompile

on:
  push:
    tags:
      - 'v*'

jobs:
  precompile:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: "dev"

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25.0.2"
          elixir-version: "1.13.4"

      - uses: goto-bus-stop/setup-zig@v1

      - name: Create precompiled library
        run: |
          export FENNEC_CACHE_DIR=$(pwd)/fennec_precompile
          mkdir -p "${FENNEC_CACHE_DIR}"
          mix deps.get
          mix compile fennec_precompile

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: fennec_precompiled/*.tar.gz
